/* =====================================================================
   SENTENCE BANK — original screenplay-style dialogue
   Format: "before the gap|after the gap|answer|alt1,alt2"
   Field 4 (alternatives) is optional.
   Add your own lines to any category — the game picks them up on reload.
   ===================================================================== */
export const BANK = {
A1: {
  "Meet the character": [
    "My name|Sarah.|is",
    "|you a police officer?|Are",
    "He|not my brother.|is",
    "We|from New York.|are",
    "|this your car?|Is",
    "I|not afraid of you.|am",
    "She|a good doctor.|is",
    "|they your friends?|Are",
    "This|not my house.|is",
    "You|late again.|are",
    "|I dead?|Am",
    "The house|empty.|is",
    "We|not alone here.|are",
    "|she your sister?|Is",
    "I|sorry for this.|am",
    "You|not safe here.|are",
    "|he your husband?|Is",
    "This|a big mistake.|is"
  ],
  "Everyday scenes": [
    "She|coffee every morning.|drinks|has",
    "He|to the gym every day.|goes",
    "|you know this man?|Do",
    "|she work here?|Does",
    "My brother|in a bank.|works",
    "I|not trust him.|do",
    "He|not answer his phone.|does",
    "The train|the station at nine.|leaves|reaches",
    "|he live near here?|Does",
    "We|not want any trouble.|do",
    "She|the truth, but she never says it.|knows",
    "|they live in this town?|Do",
    "He|his keys every day. Then he looks for them.|loses",
    "My mother|dinner at six.|makes|cooks",
    "|it rain a lot here?|Does",
    "This shop|at midnight.|closes|opens",
    "|your father like me?|Does",
    "I|not need your help.|do"
  ],
  "The apartment": [
    "There|a man at the door.|is",
    "There|two cups on the table.|are",
    "This is|old apartment.|an",
    "I need|glass of water.|a",
    "I have a key.|key is on my table.|The",
    "There|no food in the fridge.|is",
    "There|three bedrooms here.|are",
    "Look at that sky.|clouds are dark.|The",
    "I have|umbrella in my bag.|an",
    "There|a letter for you.|is",
    "I have one bag. Now I have two|.|bags",
    "There|no lights in the hall.|are",
    "I see a shadow.|shadow is near my door.|The",
    "I see|shadow near the window.|a",
    "There|a strange smell in here.|is",
    "There is one door here. All the|are locked.|doors",
    "There|many boxes in the room.|are",
    "Is there|bathroom in this apartment?|a"
  ],
  "Where and when": [
    "The cat is hiding|the table.|under|behind",
    "I live|London.|in",
    "The party is|Friday.|on",
    "We meet|nine o'clock.|at",
    "She is|the kitchen.|in",
    "Put the box|the bed, out of sight.|under",
    "The bank is|to the church.|next|close",
    "He goes|school every day.|to",
    "The keys are|the drawer.|in",
    "I will see you|Monday.|on",
    "The dog sleeps|the sofa, in the shade.|under",
    "We arrive|midnight.|at",
    "She lives|Paris now.|in",
    "Sit|to me, please.|next",
    "Come|my house tonight.|to|by",
    "The meeting is|three o'clock.|at",
    "My birthday is|July.|in",
    "The photo is|the wall.|on"
  ],
  "First lines": [
    "|are you?|How",
    "|is your name?|What",
    "|are you from?|Where",
    "|old are you?|How",
    "It's getting dark. What|is it?|time",
    "|much is this?|How",
    "|is the bathroom?|Where",
    "|is going on here?|What",
    "|do you want?|What",
    "|are we going?|Where",
    "|much do I owe you?|How",
    "|old is your dog?|How",
    "|is wrong with you?|What",
    "|is my father?|Where",
    "Nice to meet|.|you",
    "See you|.|later|soon",
    "Take|of yourself.|care",
    "I am|sorry.|so|very"
  ],
  "Asking and offering": [
    "|you help me, please?|Can",
    "Help me! I|swim!|can't|cannot",
    "She|got a car.|has",
    "I|got no money.|have",
    "|I have some water, please?|Can",
    "He|got a plan.|has",
    "The door is locked. We|leave.|can't|cannot",
    "|you pass the salt, please?|Can",
    "They|got a big house.|have",
    "|I ask you something?|Can",
    "I|got two brothers.|have",
    "She is scared of water. She|swim.|can't|cannot",
    "|you open the door for me?|Can",
    "He is too young. He|drive.|can't|cannot",
    "We|got a problem.|have",
    "|I sit here?|Can",
    "You|got beautiful eyes.|have",
    "|you keep a secret?|Can"
  ]
},
A2: {
  "Flashback": [
    "She|the door and ran into the rain.|opened",
    "He|the car keys on the table and never came back.|left",
    "Where|you go after the funeral?|did",
    "I|see anyone at the party that night.|didn't",
    "He|three miles in the dark to find her.|ran",
    "She|her keys somewhere in that old house.|lost",
    "They|to Paris without telling anyone.|went",
    "We|the news together before she disappeared.|watched|saw",
    "He|the window and climbed out to escape.|broke|opened",
    "|she tell you the secret before she left?|Did",
    "I|him at the station, right before the train left.|met",
    "She|the letter into pieces and threw it in the fire.|tore",
    "We|dinner together the night before everything changed.|had|ate",
    "He|the truth from everyone for ten years.|hid",
    "|you finish the job before they arrived?|Did",
    "She|her mind at the very last moment.|changed",
    "They|the whole story to the police the next morning.|told",
    "I|nothing about the plan until it was too late.|knew"
  ],
  "Rivals": [
    "You are|than you think, kid.|stronger|smarter,tougher,braver",
    "He is the richest man|this whole town, and everyone knows it.|in",
    "This plan is better|your last one, trust me.|than",
    "Everyone stops to watch when she performs. She is the|dancer in the whole group.|best",
    "My car is|than yours, always was.|faster",
    "He is not as|as he looks, believe me.|dangerous|tough,strong",
    "I lost my job and my dog ran away. That was the|day of my whole life.|worst",
    "You are|than your brother, but not smarter.|taller|stronger,braver,faster",
    "This is the biggest secret|the whole city right now.|in",
    "She is much more talented|her rival, and she knows it.|than",
    "He is the|liar I have ever met.|biggest|worst",
    "Our team played|than theirs tonight, finally.|better",
    "She is not as|as her brother is.|clever|smart,brave,strong,tall",
    "You think you're|than me?|smarter|better,tougher,stronger",
    "You are|clever than you look, I'll give you that.|more",
    "That's the|question of all, isn't it?|biggest|hardest",
    "Nothing is more important|the truth right now.|than",
    "She runs|than anyone else in this school.|faster"
  ],
  "The plan": [
    "I|leave town tomorrow morning.|will",
    "She is|to tell him the truth tonight.|going",
    "We|meeting him at the station at six.|are",
    "The train|at nine sharp tomorrow.|leaves|departs",
    "He|call you back later tonight.|will",
    "They are|to sell the house next month.|going",
    "I|seeing my lawyer this afternoon.|am",
    "The plane|at midnight, so hurry.|departs|leaves",
    "We|tell anyone about this.|won't",
    "Is he|to come to the wedding?|going",
    "|you help me tomorrow?|Will",
    "I|not going to wait much longer.|am",
    "She|leaving for London next week.|is",
    "The shop|at eight tomorrow morning.|opens",
    "We are|to start a new life somewhere else.|going",
    "He|be back before midnight, I promise.|will",
    "|we going to make it in time?|Are",
    "I|not forget this, ever.|will"
  ],
  "Right now": [
    "She|crying in the next room.|is",
    "|you listening to me right now?|Are",
    "We are|for the bus, and it's already late.|waiting",
    "He is|at the door — can you hear it?|knocking",
    "I am|for my keys everywhere.|searching|looking",
    "They|arguing again in the kitchen.|are",
    "What|you doing here at this hour?|are",
    "The baby|sleeping right now, be quiet.|is",
    "He is|a letter to his mother.|writing",
    "I|not lying to you.|am",
    "She is|the truth from her family.|hiding",
    "We|planning something big for tonight.|are",
    "Why|you shaking like that?|are",
    "He|standing right behind you.|is",
    "I am|to explain everything now.|trying",
    "They are|for you outside the building.|waiting|looking",
    "|she smiling? Something's wrong.|Is",
    "The phone|ringing again, answer it.|is"
  ],
  "What's left": [
    "We don't have|time left — the train leaves in five minutes!|much|any",
    "Is there|food left in the fridge, or did you eat it all?|any|some",
    "I only have|money left, about twenty dollars.|some",
    "Only a|people know the truth about that night.|few",
    "How|money do you have left?|much",
    "How|friends does he actually have?|many",
    "There's very|water left in the bottle.|little",
    "We have|choice now — we have to run.|no",
    "She has very|time to explain everything.|little",
    "There are|reasons left to trust him anymore.|no|few",
    "We need|more evidence before we can go to the police.|much|some",
    "I don't have|answers for you right now, I'm sorry.|any|many",
    "There are|things I still need to tell you, and I don't know where to start.|many|some",
    "He has|of money, but not a single real friend.|lots|plenty",
    "Almost nobody believed her, only a|people did.|few",
    "We have very|time before they find us — we need to move now.|little",
    "Do you have|questions before we start, or are you ready?|any|some",
    "There isn't|left to say — it's over between us.|much"
  ],
  "Street talk": [
    "|up! We need to leave now.|Get|Wake",
    "Turn|the lights, someone's coming.|off",
    "He|off his coat and ran into the night.|took",
    "I'm|for my brother, have you seen him?|looking",
    "I'll|you back as soon as I land.|call",
    "Please|down, you're making me nervous.|sit",
    "|on a second, I need to think.|Hold|Hang",
    "|on your coat, it's freezing outside.|Put",
    "We need to|out of here before they see us.|get",
    "Don't|up on me now, we're so close.|give",
    "I finally|out the truth about her.|found|figured",
    "Wake|! Something's wrong.|up",
    "|out! There's a car coming!|Look|Watch",
    "She|away before anyone could stop her.|ran",
    "He'll|back once he calms down.|come",
    "Turn|the radio, I love this song.|on",
    "Can you|up the phone? It's ringing.|pick",
    "Come|, we don't have all night.|on"
  ]
},
B1: {
  "The investigation": [
    "I've|seen a crime scene this messy before.|never",
    "|you ever lied to a police officer, Mr. Hale?|Have",
    "The suspect has|left the building, sir.|already",
    "We haven't found the murder weapon|.|yet",
    "She's|finished questioning the last witness.|just",
    "I have known the victim|ten years, detective.|for",
    "He hasn't spoken to anyone|the arrest last night.|since",
    "Have you ever|to that warehouse on Fifth Street?|been",
    "The footprints prove the killer has|in this room before.|been",
    "Where has he|? Nobody has seen him in hours.|gone|been",
    "This detective has|worked a case this strange.|never",
    "|the fingerprints come back from the lab yet?|Have",
    "I've|told you everything I know, so stop asking.|already",
    "She's|walked out of the interview room, so hurry.|just",
    "We've|in this town since the murder happened.|lived",
    "He has|denied being at the scene, not once.|never",
    "The forensic team has|through every room in the house.|gone|been",
    "I've|a cop for twenty years, and I've never seen anything like this.|been"
  ],
  "What if": [
    "If you|me one more lie, I'm walking out that door.|tell",
    "If you|the alarm, security will be here in two minutes.|trigger|trip",
    "I wish I|listened to my mother.|had",
    "If only I'd|the truth sooner.|known",
    "If you don't|now, you'll lose her forever.|apologize",
    "If you|water, it boils.|heat",
    "If I|rich, I'd buy a boat and sail away from this town.|were|was",
    "I wish you|here right now.|were",
    "If she|the truth, she would never forgive him.|knew|learned",
    "If we don't|now, we'll miss the last train out of the city.|leave",
    "If only you'd|to me instead of running.|talked|listened",
    "If he|late again, the boss will fire him on the spot.|is",
    "I wish I|say no to people more often.|could",
    "If you heat metal, it|.|expands",
    "If I were you, I|leave town tonight.|would|should",
    "If only we|met sooner, things could have been different.|had",
    "If you press that button, the whole building|.|explodes",
    "I wish this|never happened.|had"
  ],
  "Warnings and advice": [
    "You|tell him the truth before it's too late.|should",
    "You|go in there without backup.|mustn't|shouldn't",
    "We|leave now, or we'll miss our chance completely.|must|should",
    "You don't have|trust him, but you should listen anyway.|to",
    "It|be dangerous out there — take a coat.|might|may,could",
    "This|be a trap; keep your guard up.|may|might,could",
    "You|be joking. Tell me you're joking.|must",
    "She|know something we don't; she keeps glancing at the door.|might|could,may",
    "You don't|to come with me — it's too dangerous.|have",
    "You|be crazy to go back in there alone.|must",
    "You|to call the police right now — it's the law.|have|need",
    "He|be the one who tipped them off — nobody else knew.|could|might,may",
    "You|leave before they find you here.|should|must",
    "We|tell her the truth; she deserves to know.|should|must",
    "You|touch anything at the crime scene.|mustn't|shouldn't",
    "There|be another way out — check the back room.|might|may,could",
    "It|rain later, so bring an umbrella just in case.|may|might,could",
    "I|be wrong, but I think he's lying to us.|could|might"
  ],
  "Backstory": [
    "The man|raised me wasn't my real father.|who|that",
    "This is the house|I grew up.|where",
    "She's the woman|husband disappeared ten years ago.|whose",
    "This is the reason|I never trust strangers.|why|that",
    "The letter|changed everything is still in my drawer.|that|which",
    "I stayed quiet|I knew the truth would destroy them.|because|since",
    "He seemed kind,|he was lying the whole time.|although|but",
    "We waited|the storm finally passed.|until|till",
    "She trained for years,|she never got her chance.|but|yet",
    "I was exhausted,|I finally pulled over to sleep in the car.|so",
    "The town|I was born has changed completely.|where",
    "My brother,|left home at sixteen, never came back.|who",
    "This is the necklace|belonged to my grandmother.|which|that",
    "The doctor|treated him saved his life.|who|that",
    "|she knew the risks, she took the job anyway.|Although|Though",
    "He lost everything,|he never once complained.|but|yet",
    "This is the room|it all happened.|where",
    "I quit my job|I could take care of my mother.|so"
  ],
  "Word on the street": [
    "Someone has to|after the kids while we're gone.|look",
    "Can you look|my little sister while I run an errand?|after",
    "They decided to|off the wedding at the last minute.|call",
    "The search was called|when the weather got worse.|off",
    "I need to|out who did this before it's too late.|figure",
    "Have you figured|why he really left town?|out",
    "Don't|up on me now, not after everything we've been through.|give",
    "She refused to give|, even when everyone told her to stop.|up",
    "We're going to|out of time if we don't move now.|run",
    "The candle finally ran|, and the room went dark.|out",
    "Did you two finally|up after that argument?|make",
    "He made|the whole story just to protect her.|up",
    "You should|down everything he told you, word for word.|write",
    "She wrote|the address before she forgot it.|down|out",
    "Stop putting|the conversation — she deserves to know now.|off",
    "We can't|off this decision any longer.|put",
    "The whole town is trying to|out what really happened that night.|figure",
    "If it rains, they'll|off the ceremony until Sunday.|call"
  ],
  "Feelings": [
    "She's really good|reading people — she knew you were lying instantly.|at",
    "He's not very good|keeping secrets, so don't tell him anything.|at",
    "I heard she's married|a man she barely knows.|to",
    "Are you still married|him, or did the divorce go through?|to",
    "I'm not interested|your excuses anymore.|in",
    "She's always been interested|true crime stories.|in",
    "It all depends|whether he shows up tonight.|on|upon",
    "Whether we win depends|you now.|on|upon",
    "I owe you an apology|what I said last night.|for",
    "You should apologize|breaking her trust.|for",
    "I've been thinking|you all day.|of|about",
    "She's thinking|leaving town for good.|of|about",
    "This house belongs|my grandmother, and it always will.|to",
    "That ring belongs|the woman in the photograph.|to",
    "I'm worried|what he might do next.|about",
    "She's been worried|him since he stopped calling.|about|for",
    "He's terrible|lying — everyone can tell.|at",
    "He's good|noticing when people are lying.|at"
  ]
},
B2: {
  "The confrontation": [
    "You knew about this the whole time, and you just let it|.|slide",
    "Don't you dare walk out that|in the middle of this conversation.|door",
    "I'm not going to stand here and take the|for something I didn't do.|blame",
    "|honest with me for once in your life!|Be",
    "You've got some nerve showing your face|here.|around",
    "That's rich, coming|the person who lied to my face.|from",
    "I'm sick and tired of cleaning|your messes.|up",
    "You think you can just waltz back|like nothing happened?|in",
    "Cut the|and tell me what really happened.|nonsense",
    "I've had it|to here with your excuses.|up",
    "Don't talk|to me like I'm some kind of fool.|down",
    "You're not fooling anyone with that innocent|.|act",
    "Save your breath, I'm not buying|of it.|any",
    "Get to the|. What do you actually want from me?|point",
    "I'm done letting you walk all|me.|over",
    "You'd better watch your|, or this conversation is over.|mouth|tone,language",
    "Spare me the sob|and just tell me the truth.|story",
    "You're really going to stand there and deny it to my|?|face"
  ],
  "The heist": [
    "We need to call the whole thing|before someone gets hurt.|off",
    "If we pull this|, we'll never have to work again.|off",
    "It's too late to back|now, we're already inside.|out",
    "We need to cut|on the noise before the guards notice.|down|back",
    "Just say the word and I'll go|with the plan.|ahead",
    "There's no way they'll get|with this, not with cameras everywhere.|away",
    "I've put|with your excuses long enough, we're doing this tonight.|up",
    "The whole plan could break|if one person panics.|down",
    "Look the blueprints|one more time before we move.|over",
    "We came|a problem, the vault's been upgraded.|across",
    "The alarm's about to go|, we need to move now.|off",
    "We need to stash the cash|before anyone comes back.|away",
    "Hold on, back|for a second, how do we get past the sensors?|up",
    "Keep an eye|for security while I crack the safe.|out",
    "The signal to move in is when the lights go|.|out|off",
    "We'll split|once we're clear of the building.|up",
    "Don't cave|when the police start asking questions.|in",
    "If this goes south, we split up and lie|for a while.|low"
  ],
  "Under pressure": [
    "I'm concerned|the way this investigation is being handled.|about|with",
    "You're the one responsible|this mess, not me.|for",
    "I thought you were committed|this family.|to",
    "Don't you dare try to pin the blame|me.|on",
    "She's fully aware|what's at stake here.|of",
    "How deep are you actually involved|this?|in|with",
    "All of this chaos was caused|your carelessness.|by",
    "I've always been opposed|cutting corners on safety.|to",
    "He wasn't exactly thrilled|the news.|with|about",
    "I'm not prepared to take the blame|something I never authorized.|for",
    "You should be ashamed|yourself.|of",
    "We're all accountable|our own actions in this room.|for",
    "I'm worried|what happens if this gets out.|about",
    "This company depends entirely|your discretion.|on|upon",
    "Nobody warned me|the risks involved.|about|of",
    "I'm still not convinced|your version of events.|by",
    "You're forbidden|discussing this case outside these walls.|from",
    "I refuse to apologize|something that wasn't my fault.|for"
  ],
  "The courtroom": [
    "If I|you, I'd think very carefully before answering that question.|were|was",
    "You|better tell the truth, or this will only get worse for you.|had",
    "He acted as|he'd never seen the man before in his life.|if|though",
    "You were|to hand over the documents weeks ago.|supposed",
    "|the evidence, the jury still found him guilty.|Despite",
    "Even|he had an alibi, no one believed him.|though",
    "Bring your ID, just in|you're asked to prove your identity.|case",
    "|the time the trial started, the witness had already disappeared.|By",
    "It's high|we got some real answers from the defendant.|time",
    "No matter|hard you try, you can't talk your way out of this one.|how",
    "If she had told the truth from the start, we|be in this mess today.|wouldn't",
    "|I been in your position, I'd have called a lawyer immediately.|Had",
    "You'd|not lie to this court, Mr. Reyes.|better",
    "He talks|though he owns this courtroom.|as",
    "The defendant was|to appear at nine, yet he never showed up.|supposed",
    "Even if you|innocent, your silence makes you look guilty.|were|was",
    "In|the witness changes her story again, we need a backup plan.|case",
    "It's high time you|responsibility for what you did.|took"
  ],
  "The breakup": [
    "I gave you my whole heart, and you just threw it|.|away",
    "I should have|you the truth a long time ago.|told",
    "We've been growing apart for a|now, and we both know it.|while",
    "I've been meaning to tell you this|weeks.|for",
    "You never once asked how I was|.|feeling",
    "I was hoping you'd have changed by|, but you haven't.|now",
    "By the time you finally noticed, I'd already|on.|moved",
    "I keep wondering what I could have done|.|differently",
    "You've never been there for me, not|.|once",
    "I'm not crying because I miss you, I'm crying because I wasted so much|.|time",
    "You could have at least had the decency to tell me to my|.|face",
    "I've spent the last year convincing myself this was|.|fine",
    "We've been over for a long time, we just never said it out|.|loud",
    "I deserved better than being taken for|.|granted",
    "You promised me things would|, and nothing ever did.|change",
    "I've given you every chance, and you've wasted every one|them.|of",
    "I wish I'd walked away|.|sooner",
    "It's over. I've made up my|and there's no going back.|mind"
  ],
  "The double cross": [
    "You sold me|for a bigger cut, didn't you?|out",
    "I trusted you, and you stabbed me in the|.|back",
    "He swore he'd never|on us, and look at him now.|rat|snitch",
    "Turns|you were working for them the entire time.|out",
    "So you were in on it|the beginning?|from",
    "That so-called ally of mine was working against us the whole|.|time",
    "She played me for a|, and I fell for every word.|fool",
    "He claimed|he had no idea what was going on.|that",
    "I heard you were the one who set us|.|up",
    "You two-faced|, you were feeding them information the whole time.|snake",
    "Word on the street is you turned|for a lighter sentence.|informant",
    "He denied|involved, but the evidence says otherwise.|being",
    "I never imagined you'd be the one to double-cross|.|me",
    "She swore up and|she'd never say a word.|down",
    "She insisted|she'd had nothing to do with the leak.|that",
    "He's been reporting every move I make straight back to|.|them",
    "I should've known you were playing both|.|sides",
    "You threw me under the|the second things got difficult.|bus"
  ]
},
C1: {
  "The boardroom": [
    "The new testimony casts serious|on everything he told the board.|doubt",
    "Say what you like about her methods, but she does bear a striking|to her mother when she negotiates.|resemblance",
    "If we push the merger through this quarter, we're going to meet fierce|from the unions.|resistance|opposition",
    "After six hours of shouting, they finally reached a workable|.|compromise|solution",
    "One leaked memo could do irreparable|to this firm's reputation.|damage|harm",
    "Would you kindly pay|to the numbers on page twelve before you sign anything?|attention",
    "We need to strike the right|between ambition and recklessness, gentlemen.|balance",
    "There's been mounting|from the shareholders ever since the scandal broke.|pressure|criticism",
    "Before we vote, I want everyone to take a hard|at the fine print.|look",
    "Frankly, your explanation simply doesn't hold|, and everyone in this room knows it.|water",
    "Several members raised serious|about the timeline.|concerns|objections",
    "Approving this deal would set a dangerous|for every contract that follows.|precedent|example",
    "We've made real|on the acquisition since Tuesday.|headway|progress",
    "Let's be honest about who actually calls the|around here.|shots",
    "Read between the|, and you'll see the offer's already off the table.|lines",
    "Someone has to foot the|for this restructuring, and it won't be me.|bill",
    "Leaking that report to the press really raised the|.|stakes",
    "We're one signature away from closing the|.|deal"
  ],
  "The monologue": [
    "Not only|he lie to my face, he smiled while he said it.|did",
    "Rarely|I seen a man so certain of his own downfall.|have",
    "No sooner had the verdict been read|the courtroom erupted.|than",
    "Under no|are you to speak to the press about this case.|circumstances",
    "Only after the funeral|she learn the truth about her father's debts.|did",
    "Had I|the danger he was in, I'd never have sent him alone.|known|realized,understood",
    "Little did I|that the man I trusted most had betrayed me.|know|realize,suspect,imagine",
    "So devastating was the|that the entire cabinet resigned within a week.|leak|scandal",
    "It was the|, not the chairman, who altered the figures before the audit.|accountant|bookkeeper",
    "What I need is|, not another excuse.|answers|explanations",
    "Not only|the contract void, it exposed him to criminal charges.|was",
    "Rarely does a man|his own downfall with such composure.|face|meet,accept",
    "No sooner|the deal signed than the stock began to plummet.|was",
    "Under no circumstances|you repeat what I just told you.|must|should",
    "Only after reading the letter|he understand why she'd left.|did",
    "Had she|the truth sooner, none of this would have happened.|suspected|known,realized,discovered",
    "Little|they suspect that the merger had already been signed.|did",
    "So convinced was he of his own innocence that he refused to|a lawyer.|hire|get,retain,call"
  ],
  "The negotiation": [
    "By and|, this deal favors you far more than it favors us.|large",
    "That|, I'm not prepared to sign anything until my lawyer sees it.|said",
    "To some|, you're right — the timing couldn't be worse.|extent",
    "In|of recent developments, we're withdrawing our offer.|light",
    "If|, this only strengthens our position at the table.|anything",
    "Broadly|, both sides want the same outcome, just on different timelines.|speaking",
    "Given the|, I think we've been more than fair.|circumstances|situation",
    "We could cut costs, sure — on the other|, we'd be gutting the department.|hand",
    "It goes without|that this conversation never happened.|saying",
    "As far as I'm|, the negotiation ended the moment you threatened my family.|concerned",
    "For what it's|, I never wanted it to come to this.|worth",
    "Strictly|, you have no legal standing to make that demand.|speaking",
    "As it|, I already spoke to the board this morning.|happens",
    "Mind|, I did warn everyone this would happen.|you",
    "All things|, I think we got off lightly.|considered",
    "At the end of the|, it's your signature on the line, not mine.|day",
    "For the most|, the terms are exactly what we asked for.|part",
    "Needless to|, the offer expires at midnight.|say"
  ],
  "Idioms in play": [
    "You're barking up the wrong|.|tree",
    "Let's just play it by|and see how the meeting goes.|ear",
    "The merger's been put on the back|until the audit clears.|burner",
    "Stop beating around the|and tell me what you actually want.|bush",
    "Cut to the|— did you take the money or not?|chase",
    "I'll admit, the timing of his resignation caught me off|.|guard",
    "Losing that contract turned out to be a blessing in|.|disguise",
    "Sooner or later you're going to have to bite the|and tell her the truth.|bullet",
    "She's got a lot on her|right now, so go easy on her.|plate",
    "Winning this case is a long|, but it's not impossible.|shot",
    "Maybe you should read the|before you announce the layoffs.|room",
    "Threatening a lawsuit now would burn every|you've got left with them.|bridge",
    "Don't you dare throw me under the|when this comes out.|bus",
    "They've managed to keep the merger under|for almost a year.|wraps",
    "Someone let the cat out of the|about the layoffs before the announcement.|bag",
    "After the deal collapsed, we were back to square|.|one",
    "By the time she realized it, she was already in over her|.|head",
    "Let's call it a|— we can pick this up again tomorrow.|day"
  ],
  "The setup": [
    "We're going to have to cut|on staff if the numbers don't improve.|back|down",
    "I won't put up|his lying anymore.|with",
    "She broke|the moment they told her the diagnosis.|down",
    "The whole deal fell|when the investors pulled out.|through",
    "Can you come|with a better excuse than that?|up",
    "He backed|of the wedding two days before it happened.|out",
    "The truth finally came|during the trial.|out",
    "I might just take you|on that offer after all.|up",
    "This custody battle has dragged|for nearly three years.|on",
    "We need to go|the contract line by line before we sign.|through",
    "They called|the engagement without any explanation.|off",
    "He finally owned|to the affair in front of the whole family.|up",
    "Detectives are looking|the missing funds as we speak.|into",
    "The board refused to sign|on the merger without more data.|off",
    "The senator had to walk|his comments after the scandal broke.|back",
    "Whatever happens, I'll stand|you in that courtroom.|by",
    "Let's hold|on the announcement until legal clears it.|off",
    "Can we wrap|this meeting? I have somewhere to be.|up"
  ],
  "The reckoning": [
    "Were it|for her testimony, the whole scheme might never have unravelled.|not",
    "Had it not|for the leaked emails, he'd still be running this company.|been",
    "It later|that the signatures had been forged all along.|emerged|transpired",
    "As a direct|of his testimony, three executives lost their jobs.|result",
    "In the|of the scandal, the entire board resigned.|wake",
    "The very|that he lied about it proves he knew he was guilty.|fact",
    "It transpired|the accounts had been doctored for years.|that",
    "She refused to so much as|the possibility that she was wrong.|entertain|consider",
    "Someone has to be held|for what happened to that money.|accountable|responsible",
    "The blame ultimately|with the man who signed the check.|lies|rests",
    "Everything finally came to|when the auditor found the second ledger.|light",
    "His own arrogance was, in the|, his undoing.|end",
    "It has since been|that the report was falsified from the start.|revealed|confirmed",
    "Turns out the whole operation was rotten from the|up.|ground",
    "What brought about his|was a single, careless phone call.|downfall",
    "No one is more to|for this collapse than the man in this chair.|blame",
    "The scandal didn't just cost him his job, it cost him his|.|reputation|career,marriage",
    "Only when the files surfaced did the full extent of her|become clear.|deceit|betrayal,deception"
  ]
},
C2: {
  "Subtle idioms": [
    "She won that argument hands|, and you know it.|down",
    "Even for this family, that alibi strains|.|credulity|belief",
    "He called my closing statement 'adequate' — damned with|praise if ever I heard it.|faint",
    "Counsel, with respect, you're flogging a dead|at this point.|horse",
    "Without the ambassador's signature, the treaty is dead in the|.|water",
    "Reform the board, by all means, but let's not throw the baby out with the|.|bathwater",
    "After thirty years on the bench, she has recusal down to a fine|.|art",
    "I married the man, warts and|, and I'd do it again.|all",
    "You're not refuting my case, Your Honour, you're building a|man.|straw",
    "Burn this letter now, or it will come back to|you at the worst possible moment.|haunt|bite",
    "He never confirmed it outright; one simply had to read between the|.|lines",
    "Another leak to the press? That's par for the|these days.|course",
    "When the chairman stopped returning her calls, she saw the writing on the|.|wall",
    "Losing the seat to his own protégé was a bitter pill to|.|swallow",
    "Father and son, whatever they claim, are cut from the same|.|cloth",
    "Nobody mentioned the divorce; it sat there, the elephant in the|.|room",
    "His affair with the minister's wife was an open|among the staff for years.|secret",
    "Given the jury we selected, the verdict was something of a foregone|.|conclusion"
  ],
  "The deposition": [
    "Were it|for your untimely intervention, counsel, the settlement would have collapsed by noon.|not",
    "Suffice it to|, the witness's account did not survive cross-examination.|say",
    "Be that as it|, the contract remains binding until a court says otherwise.|may",
    "Insofar|the documents are concerned, my client has nothing further to disclose.|as",
    "Opposing counsel insisted that the witness|placed under oath a second time.|be",
    "In the event|a breach, the penalty clause shall apply retroactively.|of",
    "His objections|, the deposition proceeded exactly as scheduled.|notwithstanding|aside",
    "Should you|any objection to these terms, you must raise it before signing.|have",
    "It is imperative|the witness appear before the grand jury by Friday.|that",
    "Such|his contempt for the tribunal that he refused to rise.|was",
    "Sign nothing,|you forfeit every right of appeal.|lest",
    "No sooner|the subpoena been served than the defendant fled the jurisdiction.|had",
    "Little|the plaintiff know that the defendant had recorded every call.|did",
    "Not|the will was read did the family learn of the second marriage.|until",
    "He was, as it|, the architect of his own downfall.|were",
    "For|his protestations of innocence, the evidence told a different story.|all",
    "It|the court to consider the full record before passing sentence.|behoves|behooves",
    "Only|did counsel realise the deposition had been recorded from the outset.|then"
  ],
  "Cold power": [
    "The minister's silence only lends|to the rumours of resignation.|weight|credence",
    "She was at|to distance herself from the scandal.|pains",
    "His loyalty was, at|, negotiable.|best",
    "Her reputation seemed to|her into every room she entered.|precede",
    "It is time we drew a veil|the whole unfortunate affair.|over",
    "The question about her late husband struck a raw|.|nerve",
    "I harbour no|about his loyalty to this family.|illusions",
    "The inquiry was quietly|once the donor's name surfaced.|shelved|dropped,buried",
    "His objection was summarily|, and the hearing moved on.|dismissed",
    "Her public statement was wildly at|with what she'd told me in private.|odds",
    "The old families still hold|in this town, whatever the papers print.|sway",
    "He was told, in no uncertain|, that his services were no longer required.|terms",
    "The affair cast a long|over the rest of her career.|shadow",
    "He left the ministry under a|of suspicion.|cloud",
    "She's not above currying|with anyone who might advance her.|favour|favor",
    "The family closed|the moment the press arrived.|ranks",
    "Her irony was not lost|the committee.|on",
    "Such tactics are beneath|, even for him.|contempt"
  ],
  "The eulogy": [
    "He never asked for gratitude; by the same|, he never offered any excuses.|token",
    "For all intents and|, he raised us alone.|purposes",
    "In the final|, he judged himself far more harshly than any of us ever did.|analysis",
    "He lost the farm, and to make matters|, he never once complained.|worse",
    "By way of|, my own father never learned to say the word 'sorry.'|comparison",
    "He forgave us, time and|, for sins we never confessed to him.|again",
    "Much to my|, he kept every letter I ever sent him.|surprise",
    "Far be it|me to speak ill of the dead, but the man was insufferably stubborn.|from",
    "He nearly missed my wedding; on second|, he flew in at dawn instead.|thought|thoughts",
    "He left this world without so much|a word of complaint.|as",
    "He leaves|a wife, three children, and a garden he never quite finished.|behind",
    "In lieu of|, the family asks that you plant a tree.|flowers",
    "He kept his sense of humour till the very|.|end",
    "True to|, he insisted on paying the bill even from his hospital bed.|form",
    "As luck would|it, we scattered his ashes in the rain.|have",
    "He promised to see us through, come what|.|may",
    "For better or|, he was the only father I ever knew.|worse",
    "He wanted, in his own|, 'no fuss and no flowers.'|words"
  ],
  "The interrogation": [
    "Not|I doubt your memory, Detective, but the timeline simply doesn't hold.|that",
    "If|, his account has grown more detailed with each retelling.|anything",
    "Granted|he was present, this hardly proves guilt on its own.|that",
    "It would be|of me not to mention the missing hour in his statement.|remiss",
    "One might|that his silence spoke louder than any confession.|argue|say,suggest",
    "It was his own lawyer|first raised the question of an alibi.|who|that",
    "Little|, then, that his story changed the moment we produced the receipt.|wonder",
    "If nothing|, Detective, his fingerprints place him at the scene.|else",
    "That|, I still find his account of the evening unconvincing.|said",
    "Say what you|about him, he never once contradicted himself under oath.|will|like",
    "It goes without|that his alibi will be scrutinised line by line.|saying",
    "One cannot help|wonder why he waited three days to report it missing.|but",
    "Were I|believe every word he says, I'd still have questions about the timestamps.|to",
    "Needless to|, his fingerprints were the only ones on the weapon.|say",
    "Scarcely|he sat down when he began contradicting his own statement.|had",
    "He had|finished his account when the second witness flatly contradicted it.|hardly|barely,scarcely",
    "For what it's|, Detective, I never trusted him either.|worth",
    "He never admitted guilt, nor|he ever fully explain his absence that night.|did"
  ],
  "The last word": [
    "This conversation is|.|over|finished,done",
    "We're|here, counsellor. Don't let the door catch you on the way out.|done|finished",
    "Consider this your only|.|warning",
    "Don't mistake my courtesy for|.|weakness",
    "You'll find I don't make|twice.|threats",
    "I believe our business here is|.|concluded|finished,done,over",
    "Cross me again, and you'll regret it for the rest of your|.|life",
    "This meeting is|, ladies and gentlemen.|adjourned",
    "You have my answer, and it is|.|final",
    "Don't call again. We have nothing further to|.|discuss|say,add",
    "I trust we understand one another|.|now",
    "The court finds in favour of the|, dismissing the counterclaim entirely.|plaintiff",
    "Sentencing will be handed|at nine o'clock sharp.|down",
    "You may see yourself|.|out",
    "I believe that concludes our|.|business",
    "Take this as a professional courtesy, not a|.|favour|favor",
    "There will be no further|on the matter, Detective.|discussion|debate,comment",
    "The matter is closed. I'd advise you not to reopen|.|it"
  ]
}
};

export const LEVELS = [
  {id:"A1", name:"Beginner",           sub:"First scenes · to be, present simple, places",   c:"#00E5A0"},
  {id:"A2", name:"Elementary",         sub:"Flashbacks & plans · past, future, comparatives", c:"#00C3E3"},
  {id:"B1", name:"Intermediate",       sub:"The investigation · perfect, conditionals, modals", c:"#7B61FF"},
  {id:"B2", name:"Upper intermediate", sub:"Confrontations · phrasal verbs, real dialogue",   c:"#FF4AC1"},
  {id:"C1", name:"Advanced",           sub:"Boardrooms · inversion, hedging, idioms",         c:"#FF8A3D"},
  {id:"C2", name:"Mastery",            sub:"Cold power · register, formal structures, nuance", c:"#FFD23D"}
];
